// Generated by CoffeeScript 1.7.1
// var main_module, require, runtime;

// require = require("requirejs");

require(['runtime', 'jAgda.myscript'], function (runtime, main_module) {
  main_module.main(null)(runtime)();
});
