// Generated by CoffeeScript 1.7.1
var run;

define(["exports"], function(exports) {

run = function(c) {
  return c({
    ret: function(_,a) {
      return a;
    },
    getCanvas: function() {
      return document.getElementById("myCanvas");
    },
    getCtx: function(c) {
      return c.getContext("2d");
    },
    alert: function(s) {
      alert(s);
    },
    addEventListner: function(cb) {
      document.addEventListener('keydown',function(e) {
	 run(cb(e));
      });
    },
    mkRef: function(_,v) {
      return {ref: v};
    },
    readRef: function(_,v) {
      return v.ref;
    },
    writeRef: function(_,r,v) {
      r.ref = v;
    },
    fillStyle: function(ctx , col) {
       ctx.fillStyle = col;
    },
    fillRect: function (ctx, x , y , w, h) {
       ctx.fillRect(x,y,w,h);
    },
    setScoreText: function (s) {
       document.getElementById('score').innerHTML = s;
    },
    pacman: function (ctx, cx, cy, r, rot) {
       ctx.beginPath();
       ctx.moveTo(cx, cy);
       ctx.arc(cx, cy, r, Math.PI/6 + rot * Math.PI/2, 2 * Math.PI - Math.PI / 6 + rot * Math.PI/2,false);
       ctx.fill();
    },
    bind: function(_,_,a,b) {
          run(b (run(a)));
    }
  });
};

exports.run = run;

exports;
});
